name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app

    - name: Build and test app router
      run: xcodebuild clean build test -project AppRouter.xcodeproj -scheme "AppRouter" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.4,name=iPhone 12" ONLY_ACTIVE_ARCH=YES
